# -*- coding: utf-8 -*-
"""Feature_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNrBfXRMj38pRmmVhwfVBpXqXFKSF4D4
"""

# --- 1. Kütüphane Kurulumu ve Sistem Yolu Ayarı ---
import os
import sys
import shutil
import time
import site
from importlib import reload
import cv2
import numpy as np
import pandas as pd
from google.colab import drive

# Mediapipe'ı en temiz hali
!pip uninstall -y mediapipe
!pip install mediapipe==0.10.14 --no-cache-dir

# Colab'ın Python 3.12 yolunu sisteme zorla tanıtalım
reload(site)

sys.path.insert(0, '/usr/local/lib/python3.12/dist-packages')

# 4. ŞİMDİ TEST ET
try:
    import mediapipe as mp
    # Solutions'ı doğrudan import etmeyi dene
    from mediapipe.solutions import holistic as mp_holistic

    # Motoru test et
    test = mp_holistic.Holistic(static_image_mode=True)
    test.close()
    print("✅ SONUNDA BAŞARDIK! Motor tıkır tıkır çalışıyor.")
except Exception as e:
    print(f"❌ Hata hala devam ediyor: {e}")
    print("💡 ÇÖZÜM: Yukarıdaki menüden 'Runtime' -> 'Restart Session' yapıp bu hücreyi tekrar çalıştır.")

# Mediapipe Holistic motorunu "force-import" ile çalıştıralım
try:
    import mediapipe as mp
    from mediapipe.python.solutions import holistic as mp_holistic

    # Motorun çalışıp çalışmadığını test edelim
    test_model = mp_holistic.Holistic()
    test_model.close()
    print("✅ MÜKEMMEL: Mediapipe motoru ve alt modülleri başarıyla bağlandı!")
except Exception as e:
    print(f"❌ KRİTİK HATA: Kütüphane hala görülmüyor: {e}")

# 2. Google Drive'ı bağla
drive.mount('/content/drive')

# Drive'daki ana klasörün
drive_source = "/content/drive/MyDrive/Projects/Mobil Uygulama/largeData"
# Colab'daki çalışma alanın
colab_destination = "/content/largeData"

# Kopyalanacak klasörler (processed_data klasörünü HARİÇ tutuyoruz)
sub_folders = ['train', 'val', 'test']
# Kopyalanacak kritik dosyalar
files_to_copy = ['train_labels.csv', 'val_labels.csv', 'test_labels.csv', 'SignList_ClassId_TR_EN.csv']

def smart_copy_data():
    # 1. Hedef ana klasörü oluştur
    if not os.path.exists(colab_destination):
        os.makedirs(colab_destination)
        print(f"📁 {colab_destination} oluşturuldu.")

    print("🚀 kopyalama başladı ...")
    start_time = time.time()

    # 2. Klasörleri Tek Tek Kopyala (Sadece Video Klasörleri)
    for folder in sub_folders:
        src = os.path.join(drive_source, folder)
        dst = os.path.join(colab_destination, folder)

        if os.path.exists(src):
            if not os.path.exists(dst):
                print(f"📦 {folder} klasörü taşınıyor...")
                shutil.copytree(src, dst)
            else:
                print(f"⚠️ {folder} zaten var, atlandı.")
        else:
            print(f"❓ Uyarı: Drive'da {folder} klasörü bulunamadı!")

    # 3. CSV Dosyalarını Kopyala
    for file_name in files_to_copy:
        src_file = os.path.join(drive_source, file_name)
        dst_file = os.path.join(colab_destination, file_name)

        if os.path.exists(src_file):
            shutil.copy(src_file, dst_file)
            print(f"📄 {file_name} kopyalandı.")

    end_time = time.time()
    duration = (end_time - start_time) / 60
    print(f"\n✅ İŞLEM TAMAMLANDI!")
    print(f"⏱️ Toplam Süre: {duration:.2f} dakika.")
    print("📂 Mevcut İçerik:", os.listdir(colab_destination))

# Çalıştır
smart_copy_data()

# 1. MediaPipe Holistic Modelini Tanımla
mp_holistic = mp.solutions.holistic
holistic = mp_holistic.Holistic(
    static_image_mode=False,
    model_complexity=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)
def extract_landmarks(results):
    """
    MediaPipe sonuçlarından sağ el, sol el ve pose noktalarını süzüp
    tek bir liste (106 sayı) haline getirir.
    """
    # Sağ El (21 nokta * 2 koordinat = 42)
    rh = np.array([[res.x, res.y] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*2)

    # Sol El (21 nokta * 2 koordinat = 42)
    lh = np.array([[res.x, res.y] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*2)

    # Pose / Üst Vücut (Seçili 11 nokta * 2 koordinat = 22)
    # vücut hatlarını takip etmek için omuz, dirsek, bilek, göz ve burun noktalarını alıyoruz.
    if results.pose_landmarks:
        # MediaPipe Pose'da toplam 33 nokta vardır, biz sadece kritik olanları seçiyoruz
        # Seçilenler: 0, 2, 5, 7, 8, 11, 12, 13, 14, 15, 16 (Yüz ve Üst Gövde)
        pose_selected_indices = [0, 2, 5, 7, 8, 11, 12, 13, 14, 15, 16]
        pose = np.array([[results.pose_landmarks.landmark[i].x, results.pose_landmarks.landmark[i].y] for i in pose_selected_indices]).flatten()
    else:
        pose = np.zeros(11*2) #

    # Hepsini birleştir: 42 + 42 + 22 = 106
    return np.concatenate([rh, lh, pose])

print("✅ Koordinat çıkarma fonksiyonu hazır.")

def process_video(video_path, sequence_length=60):
    """
    Videoyu açar, her kareyi işler ve sabit uzunlukta bir dizi döndürür.
    """
    cap = cv2.VideoCapture(video_path)
    window_landmarks = []

    # 1. Videodaki her kareyi işle
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Görüntüyü işle
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = holistic.process(image)

        # Koordinatları süz ve listeye ekle
        landmarks = extract_landmarks(results)
        window_landmarks.append(landmarks)

    cap.release()

    # 2. Kare Sayısını Sabitleme (Padding veya Sampling)
    # Eğer video kısa ise son kareyi tekrar et (Padding)
    if len(window_landmarks) < sequence_length:
        diff = sequence_length - len(window_landmarks)
        last_frame = window_landmarks[-1] if len(window_landmarks) > 0 else np.zeros(106)
        for _ in range(diff):
            window_landmarks.append(last_frame)

    # Eğer video uzun ise aralardan seçerek 60 kareye düşür (Sampling)
    elif len(window_landmarks) > sequence_length:
        indices = np.linspace(0, len(window_landmarks) - 1, sequence_length, dtype=int)
        window_landmarks = [window_landmarks[i] for i in indices]

    return np.array(window_landmarks)

print("✅ Video işleme motoru hazır.")

def create_file_list(data_path):
    """
    CSV dosyalarını okur ve videoların tam yollarını etiketleriyle eşleştirir.
    """
    # Dosya yollarını belirle (Senin Drive yapına göre)
    train_csv = os.path.join(data_path, "train_labels.csv")
    val_csv = os.path.join(data_path, "val_labels.csv")
    test_csv = os.path.join(data_path, "test_labels.csv")

    # CSV'leri yükle [cite: 15, 128]
    # AUTSL formatı: video_id, label
    train_df = pd.read_csv(train_csv, names=['video_id', 'label'])
    val_df = pd.read_csv(val_csv, names=['video_id', 'label'])
    test_df = pd.read_csv(test_csv, names=['video_id', 'label'])

    print(f"📊 Eğitim videoları sayısı: {len(train_df)}") # Yaklaşık 28,142 [cite: 15, 124]
    print(f"📊 Doğrulama videoları sayısı: {len(val_df)}") # Yaklaşık 4,418 [cite: 149]
    print(f"📊 Test videoları sayısı: {len(test_df)}") # Yaklaşık 3,742 [cite: 149]

    return train_df, val_df, test_df

# Ana veri yolunu tanımla (Colab sunucusuna kopyaladığımız yer)
DATA_PATH = "/content/largeData"

try:
    train_df, val_df, test_df = create_file_list(DATA_PATH)
    print("✅ CSV dosyaları başarıyla eşleşti.")
except Exception as e:
    print(f"❌ Hata: CSV dosyaları okunamadı. Yol: {DATA_PATH}. Hata: {e}")

# Kayıt yolunu oluştur
SAVE_PATH = "/content/drive/MyDrive/Projects/Mobil Uygulama/largeData/processed_data"
if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

def safe_collect_data(df, folder_name, save_name):
    """
    Verileri parça parça işler ve kaldığı yerden devam eder.
    """
    X_final = []
    y_final = []

    # Geçici dosyaların yolu
    temp_path_X = os.path.join(SAVE_PATH, f"temp_X_{save_name}.npy")
    temp_path_y = os.path.join(SAVE_PATH, f"temp_y_{save_name}.npy")

    # 1. Eğer önceden kaydedilmiş veri varsa yükle (Resume)
    if os.path.exists(temp_path_X):
        X_final = list(np.load(temp_path_X))
        y_final = list(np.load(temp_path_y))
        print(f"🔄 {save_name} için kayıt bulundu! {len(X_final)} videodan devam ediliyor...")

    start_index = len(X_final)
    total = len(df)

    for index in range(start_index, total):
        row = df.iloc[index]
        video_name = row['video_id'] + "_color.mp4"
        video_path = os.path.join(DATA_PATH, folder_name, video_name)

        if os.path.exists(video_path):
            landmarks = process_video(video_path)
            X_final.append(landmarks)
            y_final.append(row['label'])
        else:
            # Video yoksa boş veri ekleyelim ki sıra bozulmasın (Padding gibi)
            X_final.append(np.zeros((60, 106)))
            y_final.append(row['label'])
            print(f"⚠️ Eksik video: {video_name}")

        # Her 100 videoda bir "Hayat Kurtaran" yedekleme yap
        if (index + 1) % 100 == 0 or (index + 1) == total:
            np.save(temp_path_X, np.array(X_final))
            np.save(temp_path_y, np.array(y_final))
            print(f"💾 Yedeklendi: {folder_name} -> {index + 1}/{total}")

    # İşlem tamamen bittiğinde geçici dosyayı nihai dosyaya çevir
    final_X_path = os.path.join(SAVE_PATH, f"X_{save_name}.npy")
    final_y_path = os.path.join(SAVE_PATH, f"y_{save_name}.npy")

    np.save(final_X_path, np.array(X_final))
    np.save(final_y_path, np.array(y_final))

    print(f"✅ {save_name} TAMAMLANDI ve nihai dosya oluşturuldu.")
    return np.array(X_final), np.array(y_final)

def run_extraction_v2():
    # 1. VAL
    #safe_collect_data(val_df, "val", "val")
    # 2. TEST
    #safe_collect_data(test_df, "test", "test")
    # 3. TRAIN
    safe_collect_data(train_df, "train", "train")

# Başlat
run_extraction_v2()