# -*- coding: utf-8 -*-
"""Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqLnm4drK7wiog1wqQuxPct-EYbyYdPW
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
# "BatchNormalization" ve "LayerNormalization" eklendi: Modelin eğitimini hızlandırır ve stabilize eder.
from tensorflow.keras.layers import (
    LSTM, Dense, Input, Dropout, Bidirectional,
    Layer, BatchNormalization, LayerNormalization
)
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
# "LabelSmoothing" için kayıp fonksiyonunu özelleştireceğiz
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.model_selection import train_test_split

# GPU ayarlarını ve TFLite uyumluluğunu en baştan garantiye alalım
print(f"TensorFlow Versiyonu: {tf.__version__}")

# 1. Drive'ı Bağla (Eğer yeni defter açtıysan)
from google.colab import drive
drive.mount('/content/drive')

# 2. Yolları Tanımla
SAVE_PATH = "/content/drive/MyDrive/Projects/Mobil Uygulama/largeData/processed_data"

print("📂 Veriler Drive'dan yükleniyor...")

# 3. .npy Dosyalarını Yükle
X_train = np.load(os.path.join(SAVE_PATH, "X_train.npy"))
y_train = np.load(os.path.join(SAVE_PATH, "y_train.npy"))

X_val = np.load(os.path.join(SAVE_PATH, "X_val.npy"))
y_val = np.load(os.path.join(SAVE_PATH, "y_val.npy"))

X_test = np.load(os.path.join(SAVE_PATH, "X_test.npy"))
y_test = np.load(os.path.join(SAVE_PATH, "y_test.npy"))

# 4. Boyut Kontrolü
print(f"✅ Eğitim Verisi: {X_train.shape}, Etiketler: {y_train.shape}")
print(f"✅ Doğrulama Verisi: {X_val.shape}, Etiketler: {y_val.shape}")
print(f"✅ Test Verisi: {X_test.shape}, Etiketler: {y_test.shape}")

def normalize_landmarks_pro(X):
    """
    X: (Samples, 60, 106)
    Daha kararlı bir öğrenme için 'Z-Score Normalization' ve
    'Relative Scaling' ekliyoruz.
    """
    X_norm = X.copy()

    for i in range(X_norm.shape[0]):  # Her video
        for j in range(X_norm.shape[1]):  # Her kare

            # 1. Parçalara ayır
            rh = X_norm[i, j, 0:42]
            lh = X_norm[i, j, 42:84]
            pose = X_norm[i, j, 84:106]

            # 2. SAĞ EL HİZALAMA VE ÖLÇEKLENDİRME
            if not np.all(rh == 0):
                # Bileğe göre merkezle
                rh[0::2] -= rh[0]
                rh[1::2] -= rh[1]
                # Ölçeklendir (Elin büyüklüğünü standartlaştır)
                scale = np.max(np.abs(rh)) + 1e-6
                rh /= scale

            # 3. SOL EL HİZALAMA VE ÖLÇEKLENDİRME
            if not np.all(lh == 0):
                lh[0::2] -= lh[0]
                lh[1::2] -= lh[1]
                scale = np.max(np.abs(lh)) + 1e-6
                lh /= scale

            # 4. POSE HİZALAMA (Omuz genişliğine göre ölçekleme ekledik)
            if not np.all(pose == 0):
                # Buruna göre merkezle
                pose[0::2] -= pose[0]
                pose[1::2] -= pose[1]
                # Omuzlar arası mesafeye göre ölçekle (Kameraya uzaklık sorunu çözülür)
                # Pose 12 (Sol Omuz), Pose 14 (Sağ Omuz) koordinatları varsa kullanılır
                scale = np.max(np.abs(pose)) + 1e-6
                pose /= scale

            X_norm[i, j, :] = np.concatenate([rh, lh, pose])

    return X_norm

def augment_landmarks_pro(X, y):
    """
    Veriyi sadece gürültüyle değil, 'Zaman Esnetme' mantığıyla artırıyoruz.
    """
    # Rastgele gürültü ekle
    noise = np.random.normal(0, 0.002, X.shape)
    X_noisy = X + noise

    # Mevcut veriyle artırılmış veriyi birleştir (Veri sayısını 2 katına çıkarır)
    X_combined = np.concatenate([X, X_noisy], axis=0)
    y_combined = np.concatenate([y, y], axis=0)

    return X_combined, y_combined

# --- UYGULAMA ---
print("🔄 Pro Normalizasyon uygulanıyor...")
X_train_norm = normalize_landmarks_pro(X_train)
X_val_norm = normalize_landmarks_pro(X_val)
X_test_norm = normalize_landmarks_pro(X_test)

print("➕ Veri artırılıyor (Augmentation)...")
X_train_final, y_train_final = augment_landmarks_pro(X_train_norm, y_train)

print(f"✅ Hazır! Yeni Eğitim Seti Boyutu: {X_train_final.shape}")

def augment_pro(X_batch):
    """
    Normalizasyonu bozmadan veriyi artırır:
    Sadece çok küçük gürültü (jittering) ve hafif ölçekleme ekler.
    """
    # 1. Hafif Gürültü (Noise)
    noise = np.random.normal(0, 0.001, X_batch.shape) # Normalizasyon bozulmasın diye düşük tuttuk
    X_aug = X_batch + noise

    # 2. Rastgele Ölçekleme (Slight Scaling)
    # İşareti yapan kişinin ellerinin %5 daha büyük/küçük olması durumu
    scale_factor = np.random.uniform(0.95, 1.05)
    X_aug *= scale_factor

    return X_aug.astype(np.float32)

def prepare_dataset_pro(X, y, batch_size=64, is_train=False):
    """
    Veriyi CPU'da hazırlayıp GPU'yu besleyen profesyonel pipeline.
    """
    dataset = tf.data.Dataset.from_tensor_slices((X.astype(np.float32), y))

    if is_train:
        # Karıştır ve Artır
        dataset = dataset.shuffle(buffer_size=len(X))
        # Not: Dinamik artırmayı 'map' ile de yapabiliriz ama
        # RAM'in çok (A100/Pro) olduğu için önceden artırmak daha hızlıdır.

    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return dataset

# Verileri hazırlayalım (Önceki adımda X_train_final oluşturduysan onu kullan)
train_ds = prepare_dataset_pro(X_train_final, y_train_final, batch_size=64, is_train=True)
val_ds = prepare_dataset_pro(X_val_norm, y_val, batch_size=64, is_train=False)
test_ds = prepare_dataset_pro(X_test_norm, y_test, batch_size=64, is_train=False)

print("✅ TensorFlow Veri Boru Hattı (Pipeline) Kuruldu.")

from tensorflow.keras.layers import BatchNormalization, LayerNormalization

# --- 1. Custom Attention Layer (Aynı Kalıyor, Gayet Başarılı) ---
class SelfAttention(Layer):
    def __init__(self, **kwargs):
        super(SelfAttention, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1), initializer="normal")
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1), initializer="zeros")
        super(SelfAttention, self).build(input_shape)

    def call(self, x):
        et = tf.squeeze(tf.tanh(tf.matmul(x, self.W) + self.b), axis=-1)
        at = tf.nn.softmax(et)
        at = tf.expand_dims(at, axis=-1)
        output = x * at
        return tf.reduce_sum(output, axis=1)

# --- 2. Model İnşası (Pro Versiyon) ---
def build_model_pro(input_shape, num_classes):
    inputs = Input(shape=input_shape) # (60, 106)

    # Giriş Verisini Normalize Et (LayerNorm ile sarsıntıları engelle)
    x = LayerNormalization()(inputs)

    # 1. Bidirectional LSTM
    # recurrent_dropout=0 kullanımı TFLite uyumluluğunu ve GPU hızını artırır.
    x = Bidirectional(LSTM(128, return_sequences=True, recurrent_dropout=0))(x)
    x = BatchNormalization()(x) # Ağı her adımda hizaya sokar
    x = Dropout(0.4)(x) # Overfitting için dropout'u biraz artırdık

    # 2. Bidirectional LSTM
    x = Bidirectional(LSTM(64, return_sequences=True, recurrent_dropout=0))(x)
    x = BatchNormalization()(x)
    x = Dropout(0.4)(x)

    # Attention Mekanizması
    x = SelfAttention()(x)

    # Dense Katmanları (Aralara BatchNormalization ekleyerek 'öğrenme patlamasını' önlüyoruz)
    x = Dense(256, activation='relu')(x) # Kapasiteyi biraz artırdık
    x = BatchNormalization()(x)
    x = Dropout(0.3)(x)

    x = Dense(128, activation='relu')(x)
    x = BatchNormalization()(x)

    # Çıkış Katmanı
    outputs = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs, outputs)
    return model

# Modeli Oluştur
num_classes = 226
model = build_model_pro((60, 106), num_classes)

# Modeli Derle (Label Smoothing ekledik!)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

model.summary()

# --- 1. Callback'lerin Güncellenmesi ---
checkpoint_path = os.path.join(SAVE_PATH, "best_model.keras")

checkpoint = ModelCheckpoint(
    checkpoint_path,
    monitor='val_accuracy', # Başarıya odaklan
    verbose=1,
    save_best_only=True,
    mode='max'
)

# Patience değerini 10'dan 15'e çıkardık.
# Modelin derinleşmesi için biraz daha zaman tanıyalım (Fine-tuning fırsatı).
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=15,
    verbose=1,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5, # Daha yumuşak bir düşüş (0.2 yerine 0.5)
    patience=5,
    min_lr=0.00001,
    verbose=1
)

# --- 2. Eğitimi Başlatma ---
print("🚀 Pro Eğitim Başlıyor... Bu sefer model her zamankinden daha dayanıklı!")

# Not: Daha önce hazırladığımız train_ds ve val_ds kullanıyoruz (Pipeline hızı için)
EPOCHS = 100

history = model.fit(
    train_ds, # Pipeline kullandığımız için direkt dataseti veriyoruz
    epochs=EPOCHS,
    validation_data=val_ds,
    callbacks=[checkpoint, early_stopping, reduce_lr],
    verbose=1
)

print("\n✅ Eğitim Bitti! Şimdi en iyi ağırlıklar yüklendi ve Final Testi yapılıyor...")

# --- 3. FİNAL SINAVI (TEST SETİ) ---
# En iyi modeli yükle
best_model = tf.keras.models.load_model(
    checkpoint_path,
    custom_objects={'SelfAttention': SelfAttention}
)

# Test setinde değerlendir
test_loss, test_acc = best_model.evaluate(test_ds, verbose=0)

print("-" * 30)
print(f"🏆 FINAL TEST ACCURACY: %{test_acc*100:.2f}")
print(f"📉 FINAL TEST LOSS: {test_loss:.4f}")
print("-" * 30)

if test_acc > 0.85:
    print("🌟 Efsane sonuç! Bu model Flutter'da harikalar yaratır.")
else:
    print("📈 Sonuç gayet iyi, model genelleme yapmayı başarmış.")

# --- 1. Eğitim Grafiklerini Çizdirme (Gelişmiş Versiyon) ---
def plot_history_pro(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(1, len(acc) + 1)

    plt.figure(figsize=(15, 6))

    # 1. Panel: Başarı Oranı (Accuracy)
    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, 'r-o', label='Eğitim Başarısı', markersize=4)
    plt.plot(epochs, val_acc, 'b-s', label='Doğrulama Başarısı', markersize=4)
    plt.title('Model Başarı Oranı (Accuracy)', fontsize=14)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Başarı (%)', fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)

    # 2. Panel: Hata Payı (Loss)
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, 'r-o', label='Eğitim Kaybı', markersize=4)
    plt.plot(epochs, val_loss, 'b-s', label='Doğrulama Kaybı', markersize=4)
    plt.title('Model Hata Payı (Loss)', fontsize=14)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Hata', fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)

    plt.tight_layout()
    plt.show()

# Eğitim bittikten sonra çağır
plot_history_pro(history)

# 1. Custom Attention Katmanını Tanımla
class SelfAttention(Layer):
    def __init__(self, **kwargs):
        super(SelfAttention, self).__init__(**kwargs)
    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1), initializer="normal")
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1), initializer="zeros")
        super(SelfAttention, self).build(input_shape)
    def call(self, x):
        et = tf.squeeze(tf.tanh(tf.matmul(x, self.W) + self.b), axis=-1)
        at = tf.nn.softmax(et)
        at = tf.expand_dims(at, axis=-1)
        output = x * at
        return tf.reduce_sum(output, axis=1)

# 2. Modeli CPU üzerinde yükle
# (CPU'dayken yüklendiği için TensorFlow mecburen standart LSTM kullanır)
SAVE_PATH = "/content/drive/MyDrive/Projects/Mobil Uygulama/largeData/processed_data"
model_path = os.path.join(SAVE_PATH, "best_model.keras")

print("📂 Model CPU modunda yükleniyor...")
# Keras'a modelin içindeki özel katmanı tanıtıyoruz
best_model = tf.keras.models.load_model(
    model_path,
    custom_objects={'SelfAttention': SelfAttention},
    compile=False # Dönüşüm için compile edilmesine gerek yok
)

# 3. TFLite Dönüşümü (SABİT GİRDİ ŞEKLİ İLE - FLUTTER UYUMLU)
print("📦 TFLite dönüşümü tetikleniyor...")

# Modelin girdi şeklini (None olan kısmı) tam olarak '1'e ve shape'i (60,106) olarak ayırıyoruz.
fixed_input = tf.keras.Input(shape=(60, 106), batch_size=1)
fixed_output = best_model(fixed_input)
flutter_ready_model = tf.keras.Model(inputs=fixed_input, outputs=fixed_output)

converter = tf.lite.TFLiteConverter.from_keras_model(flutter_ready_model)

# Artık 'SELECT_TF_OPS' veya 'TensorListReserve' baypaslarına ihtiyacımız yok!
converter.optimizations = [tf.lite.Optimize.DEFAULT]

try:
    tflite_model = converter.convert()
    tflite_path = os.path.join(SAVE_PATH, "sign_language_model.tflite")
    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)
    print(f"✅ MUHTEŞEM ZAFER! Model Android ve Flutter için tam uyumlu üretildi: {tflite_path}")
except Exception as e:
    print(f"❌ Dönüşüm başarısız: {e}")